// generated by `yarn tsc -p tsconfig.json` because importing ts file without this one trigger an error on ember app
var LocomotionMode;
(function (LocomotionMode) {
  LocomotionMode['ACKERMANN'] = 'ACKERMANN';
  LocomotionMode['POINT_TURN'] = 'POINT_TURN';
  LocomotionMode['CRABBING'] = 'CRABBING';
  LocomotionMode['FAKE_ACKERMANN'] = 'FAKE_ACKERMANN';
})(LocomotionMode || (LocomotionMode = {}));
export default LocomotionMode;
