export type QualityString = 'Unknown' | 'Marginal' | 'OK' | 'Good' | 'Excellent';
export type SignalQuality = { db: number; dbString: string; quality: QualityString };

export const signalQuality: Record<number, SignalQuality> = {
  0: { dbString: '-113 or less', db: -113, quality: 'Marginal' },
  1: { dbString: '-111', db: -111, quality: 'Marginal' },
  2: { dbString: '-109', db: -109, quality: 'Marginal' },
  3: { dbString: '-107', db: -107, quality: 'Marginal' },
  4: { dbString: '-105', db: -105, quality: 'Marginal' },
  5: { dbString: '-103', db: -103, quality: 'Marginal' },
  6: { dbString: '-101', db: -101, quality: 'Marginal' },
  7: { dbString: '-99', db: -99, quality: 'Marginal' },
  8: { dbString: '-97', db: -97, quality: 'Marginal' },
  9: { dbString: '-95', db: -95, quality: 'Marginal' },
  10: { dbString: '-93', db: -93, quality: 'OK' },
  11: { dbString: '-91', db: -91, quality: 'OK' },
  12: { dbString: '-89', db: -89, quality: 'OK' },
  13: { dbString: '-87', db: -87, quality: 'OK' },
  14: { dbString: '-85', db: -85, quality: 'OK' },
  15: { dbString: '-83', db: -83, quality: 'Good' },
  16: { dbString: '-81', db: -81, quality: 'Good' },
  17: { dbString: '-79', db: -79, quality: 'Good' },
  18: { dbString: '-77', db: -77, quality: 'Good' },
  19: { dbString: '-75', db: -75, quality: 'Good' },
  20: { dbString: '-73', db: -73, quality: 'Excellent' },
  21: { dbString: '-71', db: -71, quality: 'Excellent' },
  22: { dbString: '-69', db: -69, quality: 'Excellent' },
  23: { dbString: '-67', db: -67, quality: 'Excellent' },
  24: { dbString: '-65', db: -65, quality: 'Excellent' },
  25: { dbString: '-63', db: -63, quality: 'Excellent' },
  26: { dbString: '-61', db: -61, quality: 'Excellent' },
  27: { dbString: '-59', db: -59, quality: 'Excellent' },
  28: { dbString: '-57', db: -57, quality: 'Excellent' },
  29: { dbString: '-55', db: -55, quality: 'Excellent' },
  30: { dbString: '-53', db: -53, quality: 'Excellent' },
  31: { dbString: '-51 or greater', db: -51, quality: 'Excellent' },
  99: { dbString: '??', db: -999, quality: 'Unknown' },
};
